/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PhotographersIndexRouteImport } from './routes/photographers.index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as ReserveUsernameRouteImport } from './routes/reserve.$username'
import { Route as PortfolioCreateRouteImport } from './routes/portfolio.create'
import { Route as PhotographersIdRouteImport } from './routes/photographers.$id'
import { Route as GalleryCreateRouteImport } from './routes/gallery.create'
import { Route as GalleryIdRouteImport } from './routes/gallery.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographersIndexRoute = PhotographersIndexRouteImport.update({
  id: '/photographers/',
  path: '/photographers/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveUsernameRoute = ReserveUsernameRouteImport.update({
  id: '/reserve/$username',
  path: '/reserve/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioCreateRoute = PortfolioCreateRouteImport.update({
  id: '/portfolio/create',
  path: '/portfolio/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographersIdRoute = PhotographersIdRouteImport.update({
  id: '/photographers/$id',
  path: '/photographers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryCreateRoute = GalleryCreateRouteImport.update({
  id: '/gallery/create',
  path: '/gallery/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIdRoute = GalleryIdRouteImport.update({
  id: '/gallery/$id',
  path: '/gallery/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/gallery/create': typeof GalleryCreateRoute
  '/photographers/$id': typeof PhotographersIdRoute
  '/portfolio/create': typeof PortfolioCreateRoute
  '/reserve/$username': typeof ReserveUsernameRoute
  '/gallery/': typeof GalleryIndexRoute
  '/photographers/': typeof PhotographersIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/gallery/create': typeof GalleryCreateRoute
  '/photographers/$id': typeof PhotographersIdRoute
  '/portfolio/create': typeof PortfolioCreateRoute
  '/reserve/$username': typeof ReserveUsernameRoute
  '/gallery': typeof GalleryIndexRoute
  '/photographers': typeof PhotographersIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/gallery/create': typeof GalleryCreateRoute
  '/photographers/$id': typeof PhotographersIdRoute
  '/portfolio/create': typeof PortfolioCreateRoute
  '/reserve/$username': typeof ReserveUsernameRoute
  '/gallery/': typeof GalleryIndexRoute
  '/photographers/': typeof PhotographersIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/orders'
    | '/register'
    | '/gallery/$id'
    | '/gallery/create'
    | '/photographers/$id'
    | '/portfolio/create'
    | '/reserve/$username'
    | '/gallery/'
    | '/photographers/'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/orders'
    | '/register'
    | '/gallery/$id'
    | '/gallery/create'
    | '/photographers/$id'
    | '/portfolio/create'
    | '/reserve/$username'
    | '/gallery'
    | '/photographers'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/orders'
    | '/register'
    | '/gallery/$id'
    | '/gallery/create'
    | '/photographers/$id'
    | '/portfolio/create'
    | '/reserve/$username'
    | '/gallery/'
    | '/photographers/'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  OrdersRoute: typeof OrdersRoute
  RegisterRoute: typeof RegisterRoute
  GalleryIdRoute: typeof GalleryIdRoute
  GalleryCreateRoute: typeof GalleryCreateRoute
  PhotographersIdRoute: typeof PhotographersIdRoute
  PortfolioCreateRoute: typeof PortfolioCreateRoute
  ReserveUsernameRoute: typeof ReserveUsernameRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  PhotographersIndexRoute: typeof PhotographersIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographers/': {
      id: '/photographers/'
      path: '/photographers'
      fullPath: '/photographers/'
      preLoaderRoute: typeof PhotographersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/$username': {
      id: '/reserve/$username'
      path: '/reserve/$username'
      fullPath: '/reserve/$username'
      preLoaderRoute: typeof ReserveUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/create': {
      id: '/portfolio/create'
      path: '/portfolio/create'
      fullPath: '/portfolio/create'
      preLoaderRoute: typeof PortfolioCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographers/$id': {
      id: '/photographers/$id'
      path: '/photographers/$id'
      fullPath: '/photographers/$id'
      preLoaderRoute: typeof PhotographersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/create': {
      id: '/gallery/create'
      path: '/gallery/create'
      fullPath: '/gallery/create'
      preLoaderRoute: typeof GalleryCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$id': {
      id: '/gallery/$id'
      path: '/gallery/$id'
      fullPath: '/gallery/$id'
      preLoaderRoute: typeof GalleryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  OrdersRoute: OrdersRoute,
  RegisterRoute: RegisterRoute,
  GalleryIdRoute: GalleryIdRoute,
  GalleryCreateRoute: GalleryCreateRoute,
  PhotographersIdRoute: PhotographersIdRoute,
  PortfolioCreateRoute: PortfolioCreateRoute,
  ReserveUsernameRoute: ReserveUsernameRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  PhotographersIndexRoute: PhotographersIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
